services:
  - type: web
    name: academic-book-repository
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: npm start
    nodeVersion: 18.18.0
    envVars:
      - key: NODE_ENV
        value: production
